[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

; 编译选项
build_flags =
    -I NET/inc

; 链接选项 - 启用浮点打印
build_unflags = -specs=nano.specs

; 额外源文件
build_src_filter = +<*>
    +<../NET/src>